"""add_runs_table

Revision ID: 19582ffb2441
Revises: 24aaaa8cc724
Create Date: 2026-05-05 10:22:13.478126

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19582ffb2441'
down_revision: Union[str, None] = '24aaaa8cc724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table_name in inspector.get_table_names()


def _has_index(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return False
    return any(idx["name"] == index_name for idx in inspector.get_indexes(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('runs'):
        op.create_table('runs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, comment='pending | running | completed | failed | timed_out'),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_index('runs', op.f('ix_runs_session_id')):
        op.create_index(op.f('ix_runs_session_id'), 'runs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_index('runs', op.f('ix_runs_session_id')):
        op.drop_index(op.f('ix_runs_session_id'), table_name='runs')
    if _has_table('runs'):
        op.drop_table('runs')
    # ### end Alembic commands ###
