"""replace is_system_agent with capabilities

Revision ID: 6f5f935962da
Revises: 19582ffb2441
Create Date: 2026-05-05 11:01:08.879883

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5f935962da'
down_revision: Union[str, None] = '19582ffb2441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if table_name not in inspector.get_table_names():
        return False
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_column('agents', 'capabilities'):
        op.add_column('agents', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    
    # Migrate existing data
    if _has_column('agents', 'is_system_agent'):
        op.execute(
            "UPDATE agents SET capabilities = '[\"system\"]'::jsonb WHERE is_system_agent = true"
        )
    
    if _has_column('agents', 'is_system_agent'):
        op.drop_column('agents', 'is_system_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_column('agents', 'is_system_agent'):
        op.add_column('agents', sa.Column('is_system_agent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    
    # Reverse migration data
    if _has_column('agents', 'capabilities'):
        op.execute(
            "UPDATE agents SET is_system_agent = true WHERE capabilities @> '[\"system\"]'::jsonb"
        )
    
    if _has_column('agents', 'capabilities'):
        op.drop_column('agents', 'capabilities')
    # ### end Alembic commands ###
